name: Validate Frontmatter

on:
  push:
    branches:
      - frontmatter-action
  pull_request:
    branches:
      - frontmatter-action

jobs:
  validate-frontmatter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate frontmatter in markdown files
        run: |
          #!/bin/bash
          set -e
          shopt -s globstar

          # Install yq
          sudo snap install yq

          # Valid frontmatter keys
          valid_keys=("helpids" "kinds" "en_title" "title" "summary" "runtime" "installation" "stack" "tags" "guid" "version" "locale" "app_type" "isautopublish" "pageprivacy" "platform-version")

          for file in **/*.md; do
            echo "Validating frontmatter in $file"
            frontmatter=$(awk '/^---$/ {if (f) exit; else f=1}' "$file")
            if [ -z "$frontmatter" ]; then
              echo "Error: Frontmatter missing or not formatted correctly in $file"
              exit 1
            fi

            frontmatter_content=$(awk '/^---$/,/^---$/{if (!/^---$/) print}' "$file")
            frontmatter_valid=$(echo "$frontmatter_content" | yq e '.' - 2>/dev/null || true)

            if [ -z "$frontmatter_valid" ]; then
              echo "Error: Invalid YAML frontmatter in $file"
              exit 1
            else
              echo "Valid YAML frontmatter in $file"
            fi

            # Check if frontmatter contains only valid keys
            keys=$(echo "$frontmatter_valid" | yq e 'keys' -)
            invalid_keys=()
            for key in $keys; do
              key="${key%\"}"
              key="${key#\"}"
              if [[ ! " ${valid_keys[@]} " =~ " ${key} " ]]; then
                invalid_keys+=("$key")
              fi
            done

            if [ ${#invalid_keys[@]} -gt 0 ]; then
              echo "Error: Invalid frontmatter keys in $file: ${invalid_keys[*]}"
              exit 1
            else
              echo "Frontmatter contains only valid keys in $file"
            fi
          done
